### ISSUE TITLE
Clicking on character area while an event is active leaves text and buttons at bottom of screen

### ISSUE THREAD

**Issue by KalebStumbaugh** [doctor-g/social-startup-game#9]

**Comment by doctor-g** [comment]
This looks like it's related to #7 since both are using a scrolling text area. In fact, as I think about it, I bet it's because the size of these scrolling areas is passed in and cached, but during animation the size changes.

**Comment by doctor-g** [comment]
This could not be fixed quite as elegantly as #7, but I am not sure why. Using the same technique causes the text within the speech bubble to not come back after expansion: that is, the text bubble originally has text, but after being shrunk and restored, has no text. The only significant differences I can see are:
* Events area uses a fixed width rather than based on parent (probably not important)
* Events area uses AxisLayout instead of TableLayout (as in features and exploits). 
Next plan is to investigate the latter, using a degenerate one-column table layout to see if that fixes it.
